version: "2.0"

services:
  client:
    build:
      context: client/
    image: jerryauvagha/yolo_client:1.0
    entrypoint: npm start
    ports:
      - 3000:3000
    tty: true
    networks:
      - yolo_network

  backend:
    build:
      context: backend/
    image: jerryauvagha/yolo_backend:1.0
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yolomy
    entrypoint: npm start
    ports:
      - 8000:8000
    networks:
      - yolo_network
    tty: true

  mongodb:
    image: mongo:latest
    volumes:
      - yolo_volume:/data/db
    networks:
      - yolo_network

networks:
  yolo_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.128.0/24"
          gateway: "192.168.128.1"

volumes:
  yolo_volume:
